export interface ExchangeCoin {
  id: string;
  name: string;
  symbol: string;
  price: number;
  priceFormatted: string;
  changePercent: number;
  volume: string;
  tags?: string[];
  category: string[];
}

export const EXCHANGE_COINS: ExchangeCoin[] = [
  {
    id: "usdt",
    name: "테더",
    symbol: "USDT",
    price: 1457,
    priceFormatted: "1,457",
    changePercent: -0.07,
    volume: "234,841백만",
    category: ["all", "major"],
  },
  {
    id: "xrp",
    name: "엑스알피 [리플]",
    symbol: "XRP",
    price: 1985,
    priceFormatted: "1,985",
    changePercent: 0.10,
    volume: "139,529백만",
    category: ["all", "major", "rising"],
  },
  {
    id: "btc",
    name: "비트코인",
    symbol: "BTC",
    price: 96373000,
    priceFormatted: "96,373,000",
    changePercent: 0.30,
    volume: "107,825백만",
    tags: ["🔥"],
    category: ["all", "major", "rising"],
  },
  {
    id: "eth",
    name: "이더리움",
    symbol: "ETH",
    price: 2844000,
    priceFormatted: "2,844,000",
    changePercent: 0.32,
    volume: "80,363백만",
    tags: ["🔥"],
    category: ["all", "major", "rising"],
  },
  {
    id: "hum",
    name: "휴머니티",
    symbol: "H",
    price: 170,
    priceFormatted: "170",
    changePercent: 6.92,
    volume: "29,529백만",
    tags: ["주"],
    category: ["all", "rising"],
  },
  {
    id: "sol",
    name: "솔라나",
    symbol: "SOL",
    price: 120700,
    priceFormatted: "120,700",
    changePercent: 0.42,
    volume: "26,460백만",
    tags: ["🔥"],
    category: ["all", "major", "rising"],
  },
  {
    id: "sahara",
    name: "사하라에이아이",
    symbol: "SAHARA",
    price: 32.56,
    priceFormatted: "32.56",
    changePercent: -3.58,
    volume: "23,197백만",
    tags: ["주"],
    category: ["all"],
  },
  {
    id: "enso",
    name: "엔소",
    symbol: "ENSO",
    price: 2121,
    priceFormatted: "2,121",
    changePercent: 0.57,
    volume: "17,559백만",
    category: ["all", "rising"],
  },
  {
    id: "virtual",
    name: "버추얼 프로토콜",
    symbol: "VIRTUAL",
    price: 1823,
    priceFormatted: "1,823",
    changePercent: 2.14,
    volume: "15,230백만",
    category: ["all", "rising"],
  },
  {
    id: "doge",
    name: "도지코인",
    symbol: "DOGE",
    price: 225,
    priceFormatted: "225",
    changePercent: 1.05,
    volume: "12,891백만",
    category: ["all", "major", "rising"],
  },
  {
    id: "ada",
    name: "에이다",
    symbol: "ADA",
    price: 742,
    priceFormatted: "742",
    changePercent: -0.94,
    volume: "11,204백만",
    category: ["all", "major"],
  },
  {
    id: "trx",
    name: "트론",
    symbol: "TRX",
    price: 329,
    priceFormatted: "329",
    changePercent: 0.61,
    volume: "9,876백만",
    category: ["all"],
  },
  {
    id: "avax",
    name: "아발란체",
    symbol: "AVAX",
    price: 25400,
    priceFormatted: "25,400",
    changePercent: -1.23,
    volume: "8,543백만",
    category: ["all", "major"],
  },
  {
    id: "link",
    name: "체인링크",
    symbol: "LINK",
    price: 16200,
    priceFormatted: "16,200",
    changePercent: 0.87,
    volume: "7,210백만",
    category: ["all", "rising"],
  },
  {
    id: "dot",
    name: "폴카닷",
    symbol: "DOT",
    price: 4980,
    priceFormatted: "4,980",
    changePercent: -0.40,
    volume: "6,532백만",
    category: ["all"],
  },
  {
    id: "matic",
    name: "폴리곤",
    symbol: "MATIC",
    price: 532,
    priceFormatted: "532",
    changePercent: 1.34,
    volume: "5,891백만",
    category: ["all", "rising"],
  },
  {
    id: "shib",
    name: "시바이누",
    symbol: "SHIB",
    price: 0.0148,
    priceFormatted: "0.0148",
    changePercent: 3.21,
    volume: "5,120백만",
    category: ["all", "rising"],
  },
  {
    id: "atom",
    name: "코스모스",
    symbol: "ATOM",
    price: 6340,
    priceFormatted: "6,340",
    changePercent: -0.63,
    volume: "4,567백만",
    category: ["all"],
  },
];

export type ExchangeSubTab = "krw" | "btc" | "owned" | "favorites";
export type ExchangeFilter = "all" | "rising" | "major" | "minus_fee" | "sell_fee";

export const EXCHANGE_SUB_TABS: { key: ExchangeSubTab; label: string }[] = [
  { key: "krw", label: "원화" },
  { key: "btc", label: "BTC" },
  { key: "owned", label: "보유" },
  { key: "favorites", label: "관심" },
];

export const EXCHANGE_FILTERS: { key: ExchangeFilter; label: string }[] = [
  { key: "all", label: "전체" },
  { key: "rising", label: "상승신호" },
  { key: "major", label: "메이저" },
  { key: "minus_fee", label: "마이너스 수수료" },
  { key: "sell_fee", label: "매도수수료" },
];
